spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reservdb
    username: reservuser
    password: reserv


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true